In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

In [44]:
df = pd.read_csv('orders.csv')
df

,Month,New,amazon-order-id,merchant-order-id,shipment-id,shipment-item-id,amazon-order-item-id,merchant-order-item-id,purchase-date,payments-date,...,bill-country,item-promotion-discount,ship-promotion-discount,carrier,tracking-number,estimated-arrival-date,fulfillment-center-id,fulfillment-channel,sales-channel,purchase date
0,January,Y,113-8314593-5724266,NaN,DvwtVfd13,D6qfGrsxR,2.010000e+13,NaN,2020-01-31T14:55:20+00:00,2020-02-01T05:03:28+00:00,...,NaN,0.0,0.00,AMZN_US,TBA793108428000,2020-02-02T04:00:00+00:00,SLC1,AFN,Amazon.com,2020-01-31
1,January,N,114-9906705-5981823,NaN,DWb4ztvlP,DJc5FjsSR,2.540000e+13,NaN,2020-01-13T14:44:24+00:00,2020-01-14T05:12:09+00:00,...,NaN,0.0,0.00,AMZN_US,TBA665510662000,2020-01-15T04:00:00+00:00,SLC1,AFN,Amazon.com,2020-01-13
2,January,Y,111-7968236-2013013,NaN,DBR7kLxLd,DrQCL80yN,2.310000e+13,NaN,2020-01-15T21:26:15+00:00,2020-01-17T06:04:48+00:00,...,NaN,0.0,0.00,AMZN_US,TBA687827377000,2020-01-18T04:00:00+00:00,OAK4,AFN,Amazon.com,2020-01-15
3,January,Y,114-8097090-6449817,NaN,Dh6Mt756L,DtsqWQXQR,4.920000e+13,NaN,2020-01-28T13:10:15+00:00,2020-01-30T00:15:00+00:00,...,NaN,0.0,0.00,UPS,1ZWX93600376392829,2020-01-31T04:00:00+00:00,TPA1,AFN,Amazon.com,2020-01-28
4,January,Y,113-5635518-7664263,NaN,DkVd4xZJx,DHbFdnQYR,5.040000e+12,NaN,2020-01-25T17:18:06+00:00,2020-01-27T03:15:56+00:00,...,NaN,0.0,0.00,UPS,1Z6A25W50301215034,2020-01-28T04:00:00+00:00,EWR9,AFN,Amazon.com,2020-01-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380,September,Y,112-1491243-0345823,NaN,DvSK8HmK0,DNm6CXhTR,1.510000e+13,NaN,2020-09-16T07:21:40-07:00,2020-09-16T14:30:30-07:00,...,NaN,0.0,0.00,AMZN_US,TBA001206772304,2020-09-17T20:00:00-07:00,MCO1,AFN,Amazon.com,2020-09-16
2381,September,Y,113-3454474-5304209,NaN,DH016H480,DfVnJZJwN,4.860000e+12,NaN,2020-09-20T15:16:34-07:00,2020-09-21T22:27:42-07:00,...,NaN,0.0,0.00,AMZN_US,TBA005818992704,2020-09-22T20:00:00-07:00,CAE1,AFN,Amazon.com,2020-09-20
2382,September,N,113-5797949-1855408,NaN,D4w5ZDmf0,DQjNj3wrR,3.040000e+13,NaN,2020-09-16T07:46:32-07:00,2020-09-16T19:15:48-07:00,...,NaN,0.0,0.00,AMZN_US,TBA001367615604,2020-09-17T20:00:00-07:00,MDW7,AFN,Amazon.com,2020-09-16
2383,September,N,113-5797949-1855408,NaN,D4w5ZDmf0,Dpj6j1wlR,3.040000e+13,NaN,2020-09-16T07:46:32-07:00,2020-09-16T19:15:48-07:00,...,NaN,0.0,0.00,AMZN_US,TBA001367615604,2020-09-17T20:00:00-07:00,MDW7,AFN,Amazon.com,2020-09-16
2384,September,Y,112-5692313-8537033,NaN,DHpbWMkP0,DBQYSKx4N,1.760000e+13,NaN,2020-09-14T09:10:22-07:00,2020-09-18T15:20:11-07:00,...,NaN,0.0,-0.25,AMZN_US,TBA002407950604,2020-09-19T20:00:00-07:00,TPA1,AFN,Amazon.com,2020-09-14

In [8]:
orders_per_customer = df.groupby('buyer-email').count().sort_values('Month', ascending=False)

In [9]:
dist_of_order_counts = orders_per_customer.groupby('Month').count()

In [11]:
count_unique = np.sum(dist_of_order_counts['New'])

In [12]:
count_unique

1731

In [19]:
orders_by_id = df.groupby(['Month', 'amazon-order-id']).count()

In [29]:
orders_by_id_rev = df.groupby(['Month', 'amazon-order-id']).sum()

In [34]:
orders_by_id_rev.sort_values('item-price', ascending=False)
np.mean(orders_by_id_rev['quantity-shipped'])

1.2946336429308565

In [25]:
orders_by_id = orders_by_id.reset_index()

In [26]:
orders_by_id.sort_values('sku', ascending=False)

,Month,amazon-order-id,New,merchant-order-id,shipment-id,shipment-item-id,amazon-order-item-id,merchant-order-item-id,purchase-date,payments-date,...,bill-country,item-promotion-discount,ship-promotion-discount,carrier,tracking-number,estimated-arrival-date,fulfillment-center-id,fulfillment-channel,sales-channel,purchase date
1060,June,114-4099818-9597007,7,0,7,7,7,0,7,7,...,0,7,7,7,7,7,7,7,7,7
1345,May,113-3749518-2378611,7,0,7,7,7,0,7,7,...,0,7,7,7,7,7,7,7,7,7
1732,September,112-5135053-3688215,6,0,6,6,6,0,6,6,...,0,6,6,6,6,6,6,6,6,6
770,June,111-4283386-1639465,5,0,5,5,5,0,5,5,...,0,5,5,5,5,5,5,5,5,5
1005,June,113-8573954-3041812,5,0,5,5,5,0,5,5,...,0,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,July,114-2507009-2781862,1,0,1,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1
691,July,114-2470791-9301020,1,0,1,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1
690,July,114-2449612-2242619,1,0,1,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1
689,July,114-2412087-6455462,1,0,1,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1
1937,September,114-9928301-3631461,1,0,1,1,1,0,1,1,...,0,1,1,1,1,1,1,1,1,1

In [27]:
unique_orders = len(orders_by_id['New'])

1938

In [28]:
units_per_order = np.mean(orders_by_id['New'])

1.176986584107327

In [36]:
orders_by_id_rev = orders_by_id_rev.reset_index()

In [49]:
combined = df.merge(orders_by_id_rev, on='amazon-order-id')

In [50]:
combined

,Month_x,New,amazon-order-id,merchant-order-id_x,shipment-id,shipment-item-id,amazon-order-item-id_x,merchant-order-item-id_x,purchase-date,payments-date,...,ship-phone-number_y,bill-address-1_y,bill-address-2_y,bill-address-3_y,bill-city_y,bill-state_y,bill-postal-code_y,bill-country_y,item-promotion-discount_y,ship-promotion-discount_y
0,January,Y,113-8314593-5724266,NaN,DvwtVfd13,D6qfGrsxR,2.010000e+13,NaN,2020-01-31T14:55:20+00:00,2020-02-01T05:03:28+00:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
1,January,N,114-9906705-5981823,NaN,DWb4ztvlP,DJc5FjsSR,2.540000e+13,NaN,2020-01-13T14:44:24+00:00,2020-01-14T05:12:09+00:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2,January,Y,111-7968236-2013013,NaN,DBR7kLxLd,DrQCL80yN,2.310000e+13,NaN,2020-01-15T21:26:15+00:00,2020-01-17T06:04:48+00:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
3,January,Y,114-8097090-6449817,NaN,Dh6Mt756L,DtsqWQXQR,4.920000e+13,NaN,2020-01-28T13:10:15+00:00,2020-01-30T00:15:00+00:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
4,January,Y,113-5635518-7664263,NaN,DkVd4xZJx,DHbFdnQYR,5.040000e+12,NaN,2020-01-25T17:18:06+00:00,2020-01-27T03:15:56+00:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2276,September,Y,112-1491243-0345823,NaN,DvSK8HmK0,DNm6CXhTR,1.510000e+13,NaN,2020-09-16T07:21:40-07:00,2020-09-16T14:30:30-07:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2277,September,Y,113-3454474-5304209,NaN,DH016H480,DfVnJZJwN,4.860000e+12,NaN,2020-09-20T15:16:34-07:00,2020-09-21T22:27:42-07:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2278,September,N,113-5797949-1855408,NaN,D4w5ZDmf0,DQjNj3wrR,3.040000e+13,NaN,2020-09-16T07:46:32-07:00,2020-09-16T19:15:48-07:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2279,September,N,113-5797949-1855408,NaN,D4w5ZDmf0,Dpj6j1wlR,3.040000e+13,NaN,2020-09-16T07:46:32-07:00,2020-09-16T19:15:48-07:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00
2280,September,Y,112-5692313-8537033,NaN,DHpbWMkP0,DBQYSKx4N,1.760000e+13,NaN,2020-09-14T09:10:22-07:00,2020-09-18T15:20:11-07:00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.25

In [43]:
combined.columns

Index(['Month_x', 'amazon-order-id', 'merchant-order-id_x',
       'amazon-order-item-id_x', 'merchant-order-item-id_x',
       'buyer-phone-number_x', 'quantity-shipped_x', 'item-price_x',
       'item-tax_x', 'shipping-price_x', 'shipping-tax_x', 'gift-wrap-price_x',
       'gift-wrap-tax_x', 'ship-address-3_x', 'ship-phone-number_x',
       'bill-address-1_x', 'bill-address-2_x', 'bill-address-3_x',
       'bill-city_x', 'bill-state_x', 'bill-postal-code_x', 'bill-country_x',
       'item-promotion-discount_x', 'ship-promotion-discount_x', 'Month_y',
       'New', 'merchant-order-id_y', 'shipment-id', 'shipment-item-id',
       'amazon-order-item-id_y', 'merchant-order-item-id_y', 'purchase-date',
       'payments-date', 'shipment-date', 'reporting-date', 'buyer-email',
       'buyer-name', 'buyer-phone-number_y', 'sku', 'product-name',
       'quantity-shipped_y', 'currency', 'item-price_y', 'item-tax_y',
       'shipping-price_y', 'shipping-tax_y', 'gift-wrap-price_y',
       'gift-wrap-tax_y', 'ship-service-level', 'recipient-name',
       'ship-address-1', 'ship-address-2', 'ship-address-3_y', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'ship-phone-number_y',
       'bill-address-1_y', 'bill-address-2_y', 'bill-address-3_y',
       'bill-city_y', 'bill-state_y', 'bill-postal-code_y', 'bill-country_y',
       'item-promotion-discount_y', 'ship-promotion-discount_y', 'carrier',
       'tracking-number', 'estimated-arrival-date', 'fulfillment-center-id',
       'fulfillment-channel', 'sales-channel', 'purchase date'],
      dtype='object')